folder_path: './lobster_sample/data_1m_extracted/'
temp_path: './temp/'
results_path: './results'
parallel_jobs: 1
load_all_horizonts: False

experiment:
  name: 'universal_future'
  in_sample_size: 1740  # seconds
  os_size: 60
  rolling: 60

tickers: ['MS', 'MSFT']
start_date: 2017-11-24
end_date: 2017-11-24

horizont: 60

selector:
  type: 'OFI'
  volume_normalize: True
  levels: 10
  multi_horizonts: [ 1, 2, 3, 5, 10, 20, 30 ]  # multipliers

regression:
  type: 'lasso'

processor:
  normalize: False
  standardize: True


