folder_path: './lobster_sample/data_1m_extracted/'
temp_path: './temp/'
results_path: './results'
parallel_jobs: 1
load_all_horizonts: False

experiment:
  name: 'individual_future'
  in_sample_size: 1740  # seconds
  os_size: 60
  rolling: 60

tickers: [ 'AAPL']
start_date: 2017-01-01
end_date: 2017-02-01

horizont: 60

selector:
  type: 'SplitOFI'
  volume_normalize: True
  levels: 1
  multi_horizonts: [ 1, 2, 3 ]  # multipliers

regression:
  type: 'linear'

processor:
  normalize: False


