folder_path: './lobster_sample/data_10s_extracted/'
temp_path: './temp/'
results_path: './results'
parallel_jobs: 1

experiment:
  name: 'neigh_price_impact'
  in_sample_size: 1800  # seconds
  os_size: 1800
  rolling: 1800

tickers: null
start_date: 2017-01-03
end_date: 2017-01-15

selector:
  type: 'OFI'
  volume_normalize: True
  levels: 10

regression:
  type: 'linear'

processor:
  normalize: False

neighbours:
  data: 'x'
  pca: 10
  neigh_size: 5

