folder_path: './lobster_sample/data_1m_extracted/'
temp_path: './temp/'
results_path: './results'
parallel_jobs: 1
load_all_horizonts: False

experiment:
  name: 'clustered_future'
  in_sample_size: 1740  # seconds
  os_size: 60
  rolling: 60

tickers: ['AAPL', 'MSFT', 'AMZN', 'FB', 'BRK.B', 'JPM', 'GOOG', 'GOOGL', 'JNJ', 'V', 'PG', 'XOM', 'BAC', 'T', 'UNH', 'DIS', 'MA', 'INTC', 'VZ', 'HD']
start_date: 2017-01-10
end_date: 2017-01-10

horizont: 60

selector:
  type: 'SplitOFI'
  volume_normalize: True
  levels: 10
  multi_horizonts: [ 1, 2, 3 ]  # multipliers

regression:
  type: 'lasso'

processor:
  normalize: False
  standardize: False

clustering:
  data: 'x'
  pca: 10
  n_clusters: 10

